import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)
random_data=np.random.randint(1,100,50)
fig,axs=plt.subplots(2,2,figsize=(12,8))
fig.suptitle("Random integer data visualization")
axs[0,0].plot(random_data,color='red',marker='o',linestyle='-')
axs[0,0].set_title("Line chart")
axs[0,0].set_xlabel("index")
axs[0,0].set_ylabel("value")
axs[0,1].scatter(range(50),random_data,color='g',marker='x')
axs[0,1].set_title("Scatter plot")
axs[0,1].set_xlabel("index")
axs[0,1].set_ylabel("value")
axs[1,0].hist(random_data,bins=10,color='pink',alpha=0.7)
axs[1,0].set_title("Histogram plot")
axs[1,0].set_xlabel("index")
axs[1,0].set_ylabel("value")
axs[1,1].boxplot(random_data,vert=False,patch_artist=True,boxprops=dict(facecolor='yellow'))
axs[1,1].set_title("Box plot")
plt.tight_layout(rect=[0,0,1,0.95])
plt.show()
