from sklearn.preprocessing import LabelEncoder
import pandas as pd
ds=pd.read_csv('Data.csv')
print("-----------------Dataet is----------------")
print(ds)
print("-----------------Q1------------------")
print("-----------------Describing the dataset--------------")
print(ds.describe())
print("-----------------Shape of dataset------------------")
print(ds.shape)
print("-----------------First #3 rows------------------")
print(ds.head(3))
'''print("-----------------Q2------------------")
mage=ds['age'].mean()
print("Avg age:",mage)
msalary=ds['salary'].mean()
print("Avg salary:",msalary)
ds['age'].fillna(mage,inplace=True)
ds['salary'].fillna(msalary,inplace=True)
print(ds['age','salary'])'''
print("-----------------Q3------------------")
ds=pd.get_dummies(ds,columns=['country'],prefix=['country'])
le=LabelEncoder()
ds['country']=le.fit_transform(ds['country'])
ds['purchased']=le.fit_transform(ds['purchased'])
print(ds)
