import pandas as pd
import numpy as np
from sklearn import preprocessing
import scipy.stats as s
ds=pd.read_csv("winequality-red.csv")
df2=pd.DataFrame(ds)
print(ds)
print("Rescalling data:")
print("Data scalled between 0 and 1:")
data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled=data_scaler.fit_transform(df2)
print("==================================")
print(data_scaled.round(2))
print("\n Standardizing data:")
arr=np.array(ds)
print("Orignal\n:",arr)
print("\ninitial mean:",s.tmean(arr).round(2))
print("Initial standard deviation:",round(arr.std(),2))
x_scaled=preprocessing.scale(arr)
x_scaled.mean(axis=0)
x_scaled.std(axis=0)
print("Standardizing data:",arr.round(2))
print("Scaled mean:",s.tmean(arr))
print("Scaled Standard deviation:",round(arr.std(),2))
print("Normalizing")
dn=preprocessing.normalize(df2,norm='l1')
print("Normalized Data:")
print(dn.round(2))
print("Binerizing")
db=preprocessing.Binarizer(threshold=5).transform(df2)
print("Binarized Data:")
print(db.round(2))
